WITH RECURSIVE CTE AS(
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM+1 FROM CTE
    WHERE NUM < 23
)

SELECT C.NUM AS HOUR, IFNULL(A.COUNT, '0') AS COUNT FROM CTE AS C
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT FROM ANIMAL_OUTS
    GROUP BY HOUR
    ) AS A ON C.NUM = A.HOUR
ORDER BY C.NUM